#!/bin/sh
rm -f /data/hack/advancedsettings.xml
rm -f /data/hack/apps.sh
rm -f /data/hack/cache.sh
rm -f /data/hack/checkxbmc.sh
rm -f /data/hack/cleanup.sh
rm -f /data/hack/ftp.sh
rm -f /data/hack/logo.sh
rm -f /data/hack/mount.sh
rm -f /data/hack/network.sh
rm -f /data/hack/plugins.sh
rm -f /data/hack/reset.sh
rm -f /data/hack/shell.sh
rm -f /data/hack/skin.sh
rm -f /data/hack/splash.sh
rm -f /data/hack/subtitles.sh
rm -f /data/hack/telnet.sh
rm -f /data/hack/upgrade.sh
rm -f /data/hack/visualiser.sh
rm -f /data/hack/xbmc.sh
rm -f /data/hack/init.d/09upgradecleanup.sh
